//Copyright (c) Scott Butler 2014
var gw = [
    {"key": "0", "name": "Glen Waverley", "stop_id": "1078"},
    {"key": "1", "name": "Syndal", "stop_id": "1190"},
    {"key": "2", "name": "Mount Waverley", "stop_id": "1137"},
    {"key": "3", "name": "Jordanville", "stop_id": "1105"},
    {"key": "4", "name": "Holmesglen", "stop_id": "1096"},
    {"key": "5", "name": "East Malvern", "stop_id": "1058"},
    {"key": "6", "name": "Darling", "stop_id": "1051"},
    {"key": "7", "name": "Glen Iris", "stop_id": "1077"},
    {"key": "8", "name": "Gardiner", "stop_id": "1075"},
    {"key": "9", "name": "Tooronga", "stop_id": "1195"},
    {"key": "10", "name": "Kooyong", "stop_id": "1110"},
    {"key": "11", "name": "Heyington", "stop_id": "1094"},
    {"key": "12", "name": "Burnley", "stop_id": "1030"},
    {"key": "13", "name": "East Richmond", "stop_id": "1059"},
    {"key": "14", "name": "Richmond", "stop_id": "1162"},
    {"key": "15", "name": "Parliament", "stop_id": "1155"},
    {"key": "16", "name": "Melbourne Central", "stop_id": "1120"},
    {"key": "17", "name": "Flagstaff", "stop_id": "1068"},
    {"key": "18", "name": "Southern Cross", "stop_id": "1181"},
    {"key": "19", "name": "Flinders Street", "stop_id": "1071"}
];
var ld = [
    {"key": "0", "name": "Lilydale", "stop_id": "1115"},
    {"key": "1", "name": "Mooroolbark", "stop_id": "1133"},
    {"key": "2", "name": "Croydon", "stop_id": "1048"},
    {"key": "3", "name": "Ringwood East", "stop_id": "1164"},
    {"key": "4", "name": "Ringwood", "stop_id": "1163"},
    {"key": "5", "name": "Heatherdale", "stop_id": "1091"},
    {"key": "6", "name": "Mitcham", "stop_id": "1128"},
    {"key": "7", "name": "Nunawading", "stop_id": "1148"},
    {"key": "8", "name": "Blackburn", "stop_id": "1023"},
    {"key": "9", "name": "Laburnum", "stop_id": "1111"},
    {"key": "10", "name": "Box Hill", "stop_id": "1026"},
    {"key": "11", "name": "Mont Albert", "stop_id": "1129"},
    {"key": "12", "name": "Surrey Hills", "stop_id": "1189"},
    {"key": "13", "name": "Chatham", "stop_id": "1037"},
    {"key": "14", "name": "Canterbury", "stop_id": "1033"},
    {"key": "15", "name": "East Camberwell", "stop_id": "1057"},
    {"key": "16", "name": "Camberwell", "stop_id": "1032"},
    {"key": "17", "name": "Auburn", "stop_id": "1012"},
    {"key": "18", "name": "Glenferrie", "stop_id": "1080"},
    {"key": "19", "name": "Hawthorn", "stop_id": "1090"},
    {"key": "20", "name": "Burnley", "stop_id": "1030"},
    {"key": "21", "name": "East Richmond", "stop_id": "1059"},
    {"key": "22", "name": "Richmond", "stop_id": "1162"},
    {"key": "23", "name": "Parliament", "stop_id": "1155"},
    {"key": "24", "name": "Melbourne Central", "stop_id": "1120"},
    {"key": "25", "name": "Flagstaff", "stop_id": "1068"},
    {"key": "26", "name": "Southern Cross", "stop_id": "1181"},
    {"key": "27", "name": "Flinders Street", "stop_id": "1071"}
];
var bg = [
    {"key": "0", "name": "Belgrave", "stop_id": "1018"},
    {"key": "1", "name": "Tecoma", "stop_id": "1191"},
    {"key": "2", "name": "Upwey", "stop_id": "1200"},
    {"key": "4", "name": "Upper Ferntree Gully", "stop_id": "1199"},
    {"key": "6", "name": "Ferntree Gully", "stop_id": "1067"},
    {"key": "7", "name": "Boronia", "stop_id": "1025"},
    {"key": "8", "name": "Bayswater", "stop_id": "1016"},
    {"key": "9", "name": "Heathmont", "stop_id": "1092"},
    {"key": "10", "name": "Ringwood", "stop_id": "1163"},
    {"key": "11", "name": "Heatherdale", "stop_id": "1091"},
    {"key": "12", "name": "Mitcham", "stop_id": "1128"},
    {"key": "13", "name": "Nunawading", "stop_id": "1148"},
    {"key": "14", "name": "Blackburn", "stop_id": "1023"},
    {"key": "15", "name": "Laburnum", "stop_id": "1111"},
    {"key": "16", "name": "Box Hill", "stop_id": "1026"},
    {"key": "17", "name": "Mont Albert", "stop_id": "1129"},
    {"key": "18", "name": "Surrey Hills", "stop_id": "1189"},
    {"key": "19", "name": "Chatham", "stop_id": "1037"},
    {"key": "20", "name": "Canterbury", "stop_id": "1033"},
    {"key": "21", "name": "East Camberwell", "stop_id": "1057"},
    {"key": "22", "name": "Camberwell", "stop_id": "1032"},
    {"key": "23", "name": "Auburn", "stop_id": "1012"},
    {"key": "24", "name": "Glenferrie", "stop_id": "1080"},
    {"key": "25", "name": "Hawthorn", "stop_id": "1090"},
    {"key": "26", "name": "Burnley", "stop_id": "1030"},
    {"key": "27", "name": "East Richmond", "stop_id": "1059"},
    {"key": "28", "name": "Richmond", "stop_id": "1162"},
    {"key": "29", "name": "Parliament", "stop_id": "1155"},
    {"key": "30", "name": "Melbourne Central", "stop_id": "1120"},
    {"key": "31", "name": "Flagstaff", "stop_id": "1068"},
    {"key": "32", "name": "Southern Cross", "stop_id": "1181"},
    {"key": "33", "name": "Flinders Street", "stop_id": "1071"}
];
var al = [
    {"key": "0", "name": "Alamein", "stop_id": "1002"},
    {"key": "1", "name": "Ashburton", "stop_id": "1010"},
    {"key": "2", "name": "Burwood", "stop_id": "1031"},
    {"key": "3", "name": "Hartwell", "stop_id": "1087"},
    {"key": "4", "name": "Willison", "stop_id": "1213"},
    {"key": "5", "name": "Riversdale", "stop_id": "1166"},
    {"key": "6", "name": "Camberwell", "stop_id": "1032"},
    {"key": "7", "name": "Auburn", "stop_id": "1012"},
    {"key": "8", "name": "Glenferrie", "stop_id": "1080"},
    {"key": "9", "name": "Hawthorn", "stop_id": "1090"},
    {"key": "10", "name": "Burnley", "stop_id": "1030"},
    {"key": "11", "name": "East Richmond", "stop_id": "1059"},
    {"key": "12", "name": "Richmond", "stop_id": "1162"},
    {"key": "13", "name": "Parliament", "stop_id": "1155"},
    {"key": "14", "name": "Melbourne Central", "stop_id": "1120"},
    {"key": "15", "name": "Flagstaff", "stop_id": "1068"},
    {"key": "16", "name": "Southern Cross", "stop_id": "1181"},
    {"key": "17", "name": "Flinders Street", "stop_id": "1071"}
];
var cr = [
    {"key": "0", "name": "Craigieburn", "stop_id": "1044"},
    {"key": "1", "name": "Roxburgh Park", "stop_id": "1219"},
    {"key": "2", "name": "Coolaroo", "stop_id": "1221"},
    {"key": "3", "name": "Broadmeadows", "stop_id": "1028"},
    {"key": "4", "name": "Jacana", "stop_id": "1102"},
    {"key": "5", "name": "Glenroy", "stop_id": "1082"},
    {"key": "6", "name": "Oak Park", "stop_id": "1149"},
    {"key": "7", "name": "Pascoe Vale", "stop_id": "1156"},
    {"key": "8", "name": "Strathmore", "stop_id": "1186"},
    {"key": "9", "name": "Glenbervie", "stop_id": "1079"},
    {"key": "10", "name": "Essendon", "stop_id": "1064"},
    {"key": "11", "name": "Moonee Ponds", "stop_id": "1131"},
    {"key": "12", "name": "Ascot Vale", "stop_id": "1009"},
    {"key": "13", "name": "Newmarket", "stop_id": "1140"},
    {"key": "14", "name": "Kensington", "stop_id": "1108"},
    {"key": "15", "name": "North Melbourne", "stop_id": "1144"},
    {"key": "16", "name": "Flagstaff", "stop_id": "1068"},
    {"key": "17", "name": "Melbourne Central", "stop_id": "1120"},
    {"key": "18", "name": "Parliament", "stop_id": "1155"},
    {"key": "19", "name": "Southern Cross", "stop_id": "1181"},
    {"key": "20", "name": "Flinders Street", "stop_id": "1071"}
];
var cb = [
    {"key": "0", "name": "Cranbourne", "stop_id": "1045"},
    {"key": "1", "name": "Merinda Park", "stop_id": "1123"},
    {"key": "2", "name": "Lynbrook", "stop_id": "1222"},
    {"key": "3", "name": "Dandenong", "stop_id": "1049"},
    {"key": "5", "name": "Yarraman", "stop_id": "1215"},
    {"key": "6", "name": "Noble Park", "stop_id": "1142"},
    {"key": "7", "name": "Sandown Park", "stop_id": "1172"},
    {"key": "8", "name": "Springvale", "stop_id": "1183"},
    {"key": "9", "name": "Westall", "stop_id": "1208"},
    {"key": "10", "name": "Clayton", "stop_id": "1040"},
    {"key": "11", "name": "Huntingdale", "stop_id": "1099"},
    {"key": "12", "name": "Oakleigh", "stop_id": "1150"},
    {"key": "13", "name": "Hughesdale", "stop_id": "1098"},
    {"key": "14", "name": "Murrumbeena", "stop_id": "1138"},
    {"key": "15", "name": "Carnegie", "stop_id": "1034"},
    {"key": "16", "name": "Caulfield", "stop_id": "1036"},
    {"key": "17", "name": "Malvern", "stop_id": "1118"},
    {"key": "18", "name": "Armadale", "stop_id": "1008"},
    {"key": "19", "name": "Toorak", "stop_id": "1194"},
    {"key": "20", "name": "Hawksburn", "stop_id": "1089"},
    {"key": "21", "name": "South Yarra", "stop_id": "1180"},
    {"key": "22", "name": "Richmond", "stop_id": "1162"},
    {"key": "23", "name": "Parliament", "stop_id": "1155"},
    {"key": "24", "name": "Melbourne Central", "stop_id": "1120"},
    {"key": "25", "name": "Flagstaff", "stop_id": "1068"},
    {"key": "26", "name": "Southern Cross", "stop_id": "1181"},
    {"key": "27", "name": "Flinders Street", "stop_id": "1071"}
];
var fl = [
    {"key": "0", "name": "Flemington Racecourse", "stop_id": "1070"},
    {"key": "1", "name": "North Melbourne", "stop_id": "1144"},
    {"key": "2", "name": "Southern Cross", "stop_id": "1181"},
    {"key": "3", "name": "Flinders Street", "stop_id": "1071"}
];
var fr = [
    {"key": "0", "name": "Frankston", "stop_id": "1073"},
    {"key": "1", "name": "Kananook", "stop_id": "1106"},
    {"key": "2", "name": "Seaford", "stop_id": "1174"},
    {"key": "3", "name": "Carrum", "stop_id": "1035"},
    {"key": "4", "name": "Bonbeach", "stop_id": "1024"},
    {"key": "5", "name": "Chelsea", "stop_id": "1038"},
    {"key": "6", "name": "Edithvale", "stop_id": "1060"},
    {"key": "7", "name": "Aspendale", "stop_id": "1011"},
    {"key": "8", "name": "Mordialloc", "stop_id": "1134"},
    {"key": "9", "name": "Parkdale", "stop_id": "1154"},
    {"key": "10", "name": "Mentone", "stop_id": "1122"},
    {"key": "11", "name": "Cheltenham", "stop_id": "1039"},
    {"key": "12", "name": "Highett", "stop_id": "1095"},
    {"key": "13", "name": "Moorabbin", "stop_id": "1132"},
    {"key": "14", "name": "Patterson", "stop_id": "1157"},
    {"key": "15", "name": "Bentleigh", "stop_id": "1020"},
    {"key": "16", "name": "McKinnon", "stop_id": "1119"},
    {"key": "17", "name": "Ormond", "stop_id": "1152"},
    {"key": "18", "name": "Glenhuntly", "stop_id": "1081"},
    {"key": "19", "name": "Caulfield", "stop_id": "1036"},
    {"key": "20", "name": "Malvern", "stop_id": "1118"},
    {"key": "21", "name": "Armadale", "stop_id": "1008"},
    {"key": "22", "name": "Toorak", "stop_id": "1194"},
    {"key": "23", "name": "Hawksburn", "stop_id": "1089"},
    {"key": "24", "name": "South Yarra", "stop_id": "1180"},
    {"key": "25", "name": "Richmond", "stop_id": "1162"},
    {"key": "26", "name": "Parliament", "stop_id": "1155"},
    {"key": "27", "name": "Melbourne Central", "stop_id": "1120"},
    {"key": "28", "name": "Flagstaff", "stop_id": "1068"},
    {"key": "29", "name": "Southern Cross", "stop_id": "1181"},
    {"key": "30", "name": "Flinders Street", "stop_id": "1071"}
];
var hb2 = [
    {"key": "0", "name": "Hurstbridge", "stop_id": "1100"},
    {"key": "1", "name": "Wattle Glen", "stop_id": "1204"},
    {"key": "2", "name": "Diamond Creek", "stop_id": "1054"},
    {"key": "3", "name": "Eltham", "stop_id": "1062"},
    {"key": "4", "name": "Montmorency", "stop_id": "1130"},
    {"key": "5", "name": "Greensborough", "stop_id": "1084"},
    {"key": "6", "name": "Watsonia", "stop_id": "1203"},
    {"key": "7", "name": "Macleod", "stop_id": "1117"},
    {"key": "8", "name": "Rosanna", "stop_id": "1168"},
    {"key": "9", "name": "Heidelberg", "stop_id": "1093"},
    {"key": "10", "name": "Eaglemont", "stop_id": "1056"},
    {"key": "11", "name": "Ivanhoe", "stop_id": "1101"},
    {"key": "12", "name": "Darebin", "stop_id": "1050"},
    {"key": "13", "name": "Alphington", "stop_id": "1004"},
    {"key": "14", "name": "Fairfield", "stop_id": "1065"},
    {"key": "15", "name": "Dennis", "stop_id": "1053"},
    {"key": "16", "name": "Westgarth", "stop_id": "1209"},
    {"key": "17", "name": "Clifton Hill", "stop_id": "1041"},
    {"key": "18", "name": "Victoria Park", "stop_id": "1201"},
    {"key": "19", "name": "Collingwood", "stop_id": "1043"},
    {"key": "20", "name": "North Richmond", "stop_id": "1145"},
    {"key": "21", "name": "West Richmond", "stop_id": "1207"},
    {"key": "22", "name": "Jolimont-MCG", "stop_id": "1104"},
    {"key": "23", "name": "Parliament", "stop_id": "1155"},
    {"key": "24", "name": "Melbourne Central", "stop_id": "1120"},
    {"key": "25", "name": "Flagstaff", "stop_id": "1068"},
    {"key": "26", "name": "Southern Cross", "stop_id": "1181"},
    {"key": "27", "name": "Flinders Street", "stop_id": "1071"}
];
var hb = [
    {"key": "0", "name": "Hurstbridge", "stop_id": "1100"},
    {"key": "1", "name": "Wattle Glen", "stop_id": "1204"},
    {"key": "3", "name": "Diamond Creek", "stop_id": "1054"},
    {"key": "4", "name": "Eltham", "stop_id": "1062"},
    {"key": "6", "name": "Montmorency", "stop_id": "1130"},
    {"key": "7", "name": "Greensborough", "stop_id": "1084"},
    {"key": "8", "name": "Watsonia", "stop_id": "1203"},
    {"key": "9", "name": "Macleod", "stop_id": "1117"},
    {"key": "10", "name": "Rosanna", "stop_id": "1168"},
    {"key": "11", "name": "Heidelberg", "stop_id": "1093"},
    {"key": "12", "name": "Eaglemont", "stop_id": "1056"},
    {"key": "13", "name": "Ivanhoe", "stop_id": "1101"},
    {"key": "14", "name": "Darebin", "stop_id": "1050"},
    {"key": "15", "name": "Alphington", "stop_id": "1004"},
    {"key": "16", "name": "Fairfield", "stop_id": "1065"},
    {"key": "17", "name": "Dennis", "stop_id": "1053"},
    {"key": "18", "name": "Westgarth", "stop_id": "1209"},
    {"key": "19", "name": "Clifton Hill", "stop_id": "1041"},
    {"key": "20", "name": "Victoria Park", "stop_id": "1201"},
    {"key": "21", "name": "Collingwood", "stop_id": "1043"},
    {"key": "22", "name": "North Richmond", "stop_id": "1145"},
    {"key": "23", "name": "West Richmond", "stop_id": "1207"},
    {"key": "24", "name": "Jolimont-MCG", "stop_id": "1104"},
    {"key": "25", "name": "Flinders Street", "stop_id": "1071"}
];
var pa = [
    {"key": "0", "name": "Pakenham", "stop_id": "1153"},
    {"key": "1", "name": "Cardinia Road", "stop_id": "1223"},
    {"key": "2", "name": "Officer", "stop_id": "1151"},
    {"key": "3", "name": "Beaconsfield", "stop_id": "1017"},
    {"key": "4", "name": "Berwick", "stop_id": "1021"},
    {"key": "5", "name": "Narre Warren", "stop_id": "1139"},
    {"key": "6", "name": "Hallam", "stop_id": "1085"},
    {"key": "7", "name": "Dandenong", "stop_id": "1049"},
    {"key": "8", "name": "Yarraman", "stop_id": "1215"},
    {"key": "9", "name": "Noble Park", "stop_id": "1142"},
    {"key": "10", "name": "Sandown Park", "stop_id": "1172"},
    {"key": "11", "name": "Springvale", "stop_id": "1183"},
    {"key": "12", "name": "Westall", "stop_id": "1208"},
    {"key": "13", "name": "Clayton", "stop_id": "1040"},
    {"key": "14", "name": "Huntingdale", "stop_id": "1099"},
    {"key": "15", "name": "Oakleigh", "stop_id": "1150"},
    {"key": "16", "name": "Hughesdale", "stop_id": "1098"},
    {"key": "17", "name": "Murrumbeena", "stop_id": "1138"},
    {"key": "18", "name": "Carnegie", "stop_id": "1034"},
    {"key": "19", "name": "Caulfield", "stop_id": "1036"},
    {"key": "20", "name": "Malvern", "stop_id": "1118"},
    {"key": "21", "name": "Armadale", "stop_id": "1008"},
    {"key": "22", "name": "Toorak", "stop_id": "1194"},
    {"key": "23", "name": "Hawksburn", "stop_id": "1089"},
    {"key": "24", "name": "South Yarra", "stop_id": "1180"},
    {"key": "25", "name": "Richmond", "stop_id": "1162"},
    {"key": "26", "name": "Parliament", "stop_id": "1155"},
    {"key": "27", "name": "Melbourne Central", "stop_id": "1120"},
    {"key": "28", "name": "Flagstaff", "stop_id": "1068"},
    {"key": "29", "name": "Southern Cross", "stop_id": "1181"},
    {"key": "30", "name": "Flinders Street", "stop_id": "1071"}
];
var sa = [
    {"key": "0", "name": "Sandringham", "stop_id": "1173"},
    {"key": "1", "name": "Hampton", "stop_id": "1086"},
    {"key": "2", "name": "Brighton Beach", "stop_id": "1027"},
    {"key": "3", "name": "Middle Brighton", "stop_id": "1126"},
    {"key": "4", "name": "North Brighton", "stop_id": "1143"},
    {"key": "5", "name": "Gardenvale", "stop_id": "1074"},
    {"key": "6", "name": "Elsternwick", "stop_id": "1061"},
    {"key": "7", "name": "Ripponlea", "stop_id": "1165"},
    {"key": "8", "name": "Balaclava", "stop_id": "1013"},
    {"key": "9", "name": "Windsor", "stop_id": "1214"},
    {"key": "10", "name": "Prahran", "stop_id": "1158"},
    {"key": "11", "name": "South Yarra", "stop_id": "1180"},
    {"key": "12", "name": "Richmond", "stop_id": "1162"},
    {"key": "13", "name": "Flinders Street", "stop_id": "1071"}
];
var me = [
    {"key": "0", "name": "Mernda", "stop_id": "1228"},
    {"key": "1", "name": "Hawkstowe", "stop_id": "1227"},
    {"key": "2", "name": "Middle Gorge", "stop_id": "1226"},
    {"key": "3", "name": "South Morang", "stop_id": "1224"},
    {"key": "4", "name": "Epping", "stop_id": "1063"},
    {"key": "5", "name": "Lalor", "stop_id": "1112"},
    {"key": "6", "name": "Thomastown", "stop_id": "1192"},
    {"key": "7", "name": "Keon Park", "stop_id": "1109"},
    {"key": "8", "name": "Ruthven", "stop_id": "1171"},
    {"key": "9", "name": "Reservoir", "stop_id": "1161"},
    {"key": "10", "name": "Regent", "stop_id": "1160"},
    {"key": "11", "name": "Preston", "stop_id": "1159"},
    {"key": "12", "name": "Bell", "stop_id": "1019"},
    {"key": "13", "name": "Thornbury", "stop_id": "1193"},
    {"key": "14", "name": "Croxton", "stop_id": "1047"},
    {"key": "15", "name": "Northcote", "stop_id": "1147"},
    {"key": "16", "name": "Merri", "stop_id": "1125"},
    {"key": "17", "name": "Rushall", "stop_id": "1170"},
    {"key": "18", "name": "Clifton Hill", "stop_id": "1041"},
    {"key": "19", "name": "Victoria Park", "stop_id": "1201"},
    {"key": "20", "name": "Collingwood", "stop_id": "1043"},
    {"key": "21", "name": "North Richmond", "stop_id": "1145"},
    {"key": "22", "name": "West Richmond", "stop_id": "1207"},
    {"key": "23", "name": "Jolimont-MCG", "stop_id": "1104"},
    {"key": "24", "name": "Parliament", "stop_id": "1155"},
    {"key": "25", "name": "Melbourne Central", "stop_id": "1120"},
    {"key": "26", "name": "Flagstaff", "stop_id": "1068"},
    {"key": "27", "name": "Southern Cross", "stop_id": "1181"},
    {"key": "28", "name": "Flinders Street", "stop_id": "1071"}
];
var sp = [
    {"key": "0", "name": "Stony Point", "stop_id": "1185"},
    {"key": "1", "name": "Crib Point", "stop_id": "1046"},
    {"key": "2", "name": "Morradoo", "stop_id": "1136"},
    {"key": "3", "name": "Bittern", "stop_id": "1022"},
    {"key": "4", "name": "Hastings", "stop_id": "1088"},
    {"key": "5", "name": "Tyabb", "stop_id": "1197"},
    {"key": "6", "name": "Somerville", "stop_id": "1178"},
    {"key": "7", "name": "Baxter", "stop_id": "1015"},
    {"key": "8", "name": "Leawarra", "stop_id": "1114"},
    {"key": "9", "name": "Frankston", "stop_id": "1073"}
];
var su = [
    {"key": "0", "name": "Sunbury", "stop_id": "1187"},
    {"key": "1", "name": "Diggers Rest", "stop_id": "1055"},
    {"key": "2", "name": "Watergardens", "stop_id": "1202"},
    {"key": "3", "name": "Keilor Plains", "stop_id": "1107"},
    {"key": "4", "name": "St Albans", "stop_id": "1184"},
    {"key": "5", "name": "Ginifer", "stop_id": "1076"},
    {"key": "6", "name": "Albion", "stop_id": "1003"},
    {"key": "7", "name": "Sunshine", "stop_id": "1218"},
    {"key": "8", "name": "Tottenham", "stop_id": "1196"},
    {"key": "9", "name": "West Footscray", "stop_id": "1206"},
    {"key": "10", "name": "Middle Footscray", "stop_id": "1127"},
    {"key": "11", "name": "Footscray", "stop_id": "1072"},
    {"key": "12", "name": "North Melbourne", "stop_id": "1144"},
    {"key": "13", "name": "Flagstaff", "stop_id": "1068"},
    {"key": "14", "name": "Melbourne Central", "stop_id": "1120"},
    {"key": "15", "name": "Parliament", "stop_id": "1155"},
    {"key": "16", "name": "Southern Cross", "stop_id": "1181"},
    {"key": "17", "name": "Flinders Street", "stop_id": "1071"}
];
var uf = [
    {"key": "0", "name": "Upfield", "stop_id": "1198"},
    {"key": "1", "name": "Gowrie", "stop_id": "1083"},
    {"key": "2", "name": "Fawkner", "stop_id": "1066"},
    {"key": "3", "name": "Merlynston", "stop_id": "1124"},
    {"key": "4", "name": "Batman", "stop_id": "1014"},
    {"key": "5", "name": "Coburg", "stop_id": "1042"},
    {"key": "6", "name": "Moreland", "stop_id": "1135"},
    {"key": "7", "name": "Anstey", "stop_id": "1006"},
    {"key": "8", "name": "Brunswick", "stop_id": "1029"},
    {"key": "9", "name": "Jewell", "stop_id": "1103"},
    {"key": "10", "name": "Royal Park", "stop_id": "1169"},
    {"key": "11", "name": "Flemington Bridge", "stop_id": "1069"},
    {"key": "12", "name": "Macaulay", "stop_id": "1116"},
    {"key": "13", "name": "North Melbourne", "stop_id": "1144"},
    {"key": "14", "name": "Flagstaff", "stop_id": "1068"},
    {"key": "15", "name": "Melbourne Central", "stop_id": "1120"},
    {"key": "16", "name": "Parliament", "stop_id": "1155"},
    {"key": "17", "name": "Southern Cross", "stop_id": "1181"},
    {"key": "18", "name": "Flinders Street", "stop_id": "1071"}
];
var we = [
    {"key": "0", "name": "Werribee", "stop_id": "1205"},
    {"key": "1", "name": "Hoppers Crossing", "stop_id": "1097"},
    {"key": "2", "name": "Williams Landing", "stop_id": "1225"},
    {"key": "3", "name": "Aircraft", "stop_id": "1220"},
    {"key": "4", "name": "Laverton", "stop_id": "1113"},
    {"key": "5", "name": "Westona", "stop_id": "1210"},
    {"key": "7", "name": "Altona", "stop_id": "1005"},
    {"key": "8", "name": "Seaholme", "stop_id": "1175"},
    {"key": "9", "name": "Newport", "stop_id": "1141"},
    {"key": "10", "name": "Spotswood", "stop_id": "1182"},
    {"key": "11", "name": "Yarraville", "stop_id": "1216"},
    {"key": "12", "name": "Seddon", "stop_id": "1176"},
    {"key": "13", "name": "Footscray", "stop_id": "1072"},
    {"key": "14", "name": "South Kensington", "stop_id": "1179"},
    {"key": "15", "name": "North Melbourne", "stop_id": "1144"},
    {"key": "16", "name": "Flagstaff", "stop_id": "1068"},
    {"key": "17", "name": "Melbourne Central", "stop_id": "1120"},
    {"key": "18", "name": "Parliament", "stop_id": "1155"},
    {"key": "19", "name": "Southern Cross", "stop_id": "1181"},
    {"key": "20", "name": "Flinders Street ARR", "stop_id": "1071"}
];
var wi = [
    {"key": "0", "name": "Williamstown", "stop_id": "1211"},
    {"key": "1", "name": "Williamstown Beach", "stop_id": "1212"},
    {"key": "2", "name": "North Williamstown", "stop_id": "1146"},
    {"key": "3", "name": "Newport", "stop_id": "1141"},
    {"key": "4", "name": "Spotswood", "stop_id": "1182"},
    {"key": "5", "name": "Yarraville", "stop_id": "1216"},
    {"key": "6", "name": "Seddon", "stop_id": "1176"},
    {"key": "7", "name": "Footscray", "stop_id": "1072"},
    {"key": "8", "name": "South Kensington", "stop_id": "1179"},
    {"key": "9", "name": "North Melbourne", "stop_id": "1144"},
    {"key": "10", "name": "Flagstaff", "stop_id": "1068"},
    {"key": "11", "name": "Melbourne Central", "stop_id": "1120"},
    {"key": "12", "name": "Parliament", "stop_id": "1155"},
    {"key": "13", "name": "Southern Cross", "stop_id": "1181"},
    {"key": "14", "name": "Flinders Street", "stop_id": "1071"}
];
 
var Lines = [
    {"name": "Glen Waverley", "data": gw, "id": 7},
    {"name": "Lilydale", "data": ld, "id": 9},
    {"name": "Belgrave", "data": bg, "id": 2},
    {"name": "Alamein", "data": al, "id": 1},
    {"name": "Craigieburn", "data": cr, "id": 3},
    {"name": "Cranbourne", "data": cb, "id": 4},
    {"name": "Flemington Racecourse", "data": fl},
    {"name": "Frankston", "data": fr, "id": 6},
    {"name": "Hurstbridge", "data": hb, "id": 8},
    {"name": "Pakenham", "data": pa, "id": 11},
    {"name": "Sandringham", "data": sa, "id": 12},
    {"name": "Mernda", "data": me, "id": 5},
    {"name": "Stony Point", "data": sp, "id": 13},
    {"name": "Sunbury", "data": su, "id": 14},
    {"name": "Upfield", "data": uf, "id": 15},
    {"name": "Werribee", "data": we, "id": 16},
    {"name": "Williamstown", "data": wi, "id": 17}
];

function getLine(id) {
    for (let i = 0; i < Lines.length; i++) {
        const line = Lines[i];
        if (line.id === id) return line;
    }
    return {"name": "Unknown line", "data": [], "id": 0};
}